export const SEMANTICODE_ROUTE_BASE = '/__semanticode'
export const SEMANTICODE_ROUTE =
  `${SEMANTICODE_ROUTE_BASE}/snapshot`
export const SEMANTICODE_LAYOUTS_ROUTE =
  `${SEMANTICODE_ROUTE_BASE}/layouts`
export const SEMANTICODE_PREPROCESSING_ROUTE =
  `${SEMANTICODE_ROUTE_BASE}/preprocessing`
export const SEMANTICODE_SYNC_ROUTE =
  `${SEMANTICODE_ROUTE_BASE}/sync`
export const SEMANTICODE_PREPROCESSING_SUMMARY_ROUTE =
  `${SEMANTICODE_PREPROCESSING_ROUTE}/summary`
export const SEMANTICODE_PREPROCESSING_EMBEDDINGS_ROUTE =
  `${SEMANTICODE_PREPROCESSING_ROUTE}/embeddings`
export const SEMANTICODE_DRAFTS_ROUTE =
  `${SEMANTICODE_ROUTE_BASE}/drafts`
export const SEMANTICODE_AGENT_ROUTE_BASE =
  `${SEMANTICODE_ROUTE_BASE}/agent`
export const SEMANTICODE_AGENT_SESSION_ROUTE =
  `${SEMANTICODE_AGENT_ROUTE_BASE}/session`
export const SEMANTICODE_AGENT_MESSAGE_ROUTE =
  `${SEMANTICODE_AGENT_ROUTE_BASE}/message`
export const SEMANTICODE_AGENT_CANCEL_ROUTE =
  `${SEMANTICODE_AGENT_ROUTE_BASE}/cancel`
export const SEMANTICODE_AGENT_SETTINGS_ROUTE =
  `${SEMANTICODE_AGENT_ROUTE_BASE}/settings`
export const SEMANTICODE_AGENT_AUTH_ROUTE_BASE =
  `${SEMANTICODE_AGENT_ROUTE_BASE}/auth`
export const SEMANTICODE_AGENT_AUTH_SESSION_ROUTE =
  `${SEMANTICODE_AGENT_AUTH_ROUTE_BASE}/session`
export const SEMANTICODE_AGENT_AUTH_LOGIN_START_ROUTE =
  `${SEMANTICODE_AGENT_AUTH_ROUTE_BASE}/login/start`
export const SEMANTICODE_AGENT_AUTH_COMPLETE_ROUTE =
  `${SEMANTICODE_AGENT_AUTH_ROUTE_BASE}/complete`
export const SEMANTICODE_AGENT_AUTH_LOGOUT_ROUTE =
  `${SEMANTICODE_AGENT_AUTH_ROUTE_BASE}/logout`
export const SEMANTICODE_AGENT_AUTH_IMPORT_CODEX_ROUTE =
  `${SEMANTICODE_AGENT_AUTH_ROUTE_BASE}/import-codex`
export const SEMANTICODE_AGENT_AUTH_CALLBACK_ROUTE =
  `${SEMANTICODE_AGENT_AUTH_ROUTE_BASE}/callback`

export function buildSemanticodeDraftActionRoute(
  draftId: string,
  action: 'accept' | 'reject',
) {
  return `${SEMANTICODE_DRAFTS_ROUTE}/${encodeURIComponent(draftId)}/${action}`
}
